argo-cd: # dependency in the Chart.yaml 
  dex:
    enabled: true
  notifications:
    enabled: true
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
  # Dex config
  config:
    admin.enabled: "true"
    dex.config: |-
      logger:
        level: debug
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: 5e4280f65aba9e013f44
          clientSecret: $argo-dex-github-sso.github.clientSecret
          loadAllGroups: true
          orgs:
          - name: gft-blx
    url: http://localhost:8088
