argo-cd: # dependency in the Chart.yaml 
  dex:
    enabled: true
  notifications:
    enabled: true
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
  configs:
    # Dex configuration
    dex.config: |
      connectors:
        # GitHub example
        - type: github
          id: github
          name: GitHub
          config:
            clientID: 5e4280f65aba9e013f44
            clientSecret: $argo-dex-github-sso.github.clientSecret # Alternatively $<some_K8S_secret>:dex.github.clientSecret
            orgs:
            - name: gft-blx
