argo-cd: # dependency in the Chart.yaml 
  notifications:
    enabled: true
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
  # Dex config
  dex:
    enabled: true
            
