apiVersion: v1
kind: Secret
metadata:
  name: argo-dex-github-sso
  namespace: myargo-local
  labels:
    app.kubernetes.io/part-of: argocd
data:
  githubOauthClientID: 5e4280f65aba9e013f44
  githubOauthClientSecret: a0e94188687e10744823a2812bf2f973649b9e23
  # Oauth app client id for testing
